---
title: "Analyses_donnees_2024"
author: "Adrien Debout"
date: "2025-04-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Environnement

```{r}
library(here) # environnement de travail
library(readxl)
library(dplyr) # mise en forme des tableaux
library(tidyverse)
library(stringr)
library(ggplot2) # ggplot graphiques
library(gridExtra) # Afficher plusieurs ggplots en meme temps
library(fitdistrplus) # Regarder la distribution la mieux adaptée
library(glmmTMB) # modèles mixtes
library(AICcmodavg) # Comparaison de modèles
library(fitdistrplus) # Distribution la mieux adaptée
library(DHARMa) # Vérification des présuposés des modèles
library(emmeans)
library(multcomp)
library(vegan)
library(tidyr)
```

# 2. working directory

```{r}
  # Working diretory
setwd(here::here("Data", "Data entomo"))
here()
```

# 3. Tests & graphs initiaux

```{r}
  # IMPORT Jeu de données coléoptères
Coleo <- read.table("jeu_donnees_coleo.txt", sep = "\t", dec = ".", quote = "\"", stringsAsFactors = F, header = T) %>%
  select(6 : 7, 10 : 20)

  # Calcul de l'abondance par piège
abondance <- Coleo %>%
  group_by(Numero_de_piege) %>%
  summarise(Abondance = sum(Abondance))
  # Graphique de visualisation 
ab <- ggplot(abondance, aes(x = Numero_de_piege, y = Abondance)) +
  geom_bar(stat = "identity", fill = c("darkgreen", "#458B00", "#556B2F", "#9ACD32")) +
  geom_text(aes(label = Abondance), vjust = -0.5, size = 3) +
  labs(title = "Abondance de coléoptères saproxyliques le long des arbres Thèses",
       x = "Pièges entomologiques",
       y = "Abondance (n)") +
  ylim(0, 10000) +
  theme_minimal() +
  theme(plot.title = element_text(size = 9, face = "bold"),
    axis.text.x = element_text(angle = 0))

# Div1 <- Coleo %>%
#   filter(Numero_de_piege == "1") %>%
#   distinct(SP, .keep_all = T) %>%
#   select(9, 13) %>%
#   mutate(nbesp = 1) %>%
#   summarise(nbesp = sum(nbesp)) %>%
#   mutate(piege = "Piege_1")
# Div2 <- Coleo %>%
#   filter(Numero_de_piege == "2") %>%
#   distinct(SP, .keep_all = T) %>%
#   select(9, 13) %>%
#   mutate(nbesp = 1) %>%
#   summarise(nbesp = sum(nbesp)) %>%
#   mutate(piege = "Piege_2")
# Div3 <- Coleo %>%
#   filter(Numero_de_piege == "3") %>%
#   distinct(SP, .keep_all = T) %>%
#   select(9, 13) %>%
#   mutate(nbesp = 1) %>%
#   summarise(nbesp = sum(nbesp)) %>%
#   mutate(piege = "Piege_3")
# Div4 <- Coleo %>%
#   filter(Numero_de_piege == "4") %>%
#   distinct(SP, .keep_all = T) %>%
#   select(9, 13) %>%
#   mutate(nbesp = 1) %>%
#   summarise(nbesp = sum(nbesp)) %>%
#   mutate(piege = "Piege_4")
# Div <- bind_rows(Div1, Div2, Div3, Div4) %>%
#   arrange(piege)

  # 
# div_coleo <- Coleo %>%
#   distinct(SP, .keep_all = T) %>%
#   select(9, 13) %>%
#   mutate(SP = ifelse(SP == "", NA, SP),
#          nbesp = 1) %>%
#   filter(!is.na(SP)) %>%
#   group_by(Numero_de_piege) %>%
#   summarise(nbesp = sum(nbesp))


div_coleo <- Coleo %>%
  distinct(Espece, Numero_de_piege, .keep_all = T) %>%
  select(6, 11, 13)
#
div1 <- div_coleo %>%
  filter(Numero_de_piege == 1)
#
div2 <- div_coleo %>%
  filter(Numero_de_piege == 2)
#
div3 <- div_coleo %>%
  filter(Numero_de_piege == 3)
#
div4 <- div_coleo %>%
  filter(Numero_de_piege == 4)

#

div <- ggplot(div_coleo, aes(x = Numero_de_piege, y = nbesp)) +
  geom_bar(stat = "identity", fill = c("darkgreen", "#458B00", "#556B2F", "#9ACD32")) +
  geom_text(aes(label = nbesp), vjust = -0.5, size = 3) +
  labs(title = "Diversité spécifique dans chaque pièges des arbres Thèses",
       x = "Pièges entomologiques",
       y = "Diversité spécifique") +
  ylim(0, 100) +
  theme_minimal() +
  theme(plot.title = element_text(size = 9, face = "bold"),
        axis.text.x = element_text(angle = 0))
  # Faire apparaître 2 ggplot en même temps
grid.arrange(ab, div, ncol = 2)

#

Coleobis <- Coleo %>%
  select(8, 9, 11, 13) %>%
  mutate(code_sp = ifelse((is.na(GEN) | GEN == "") & (is.na(SP) | SP == ""), "INC",
         paste(GEN, SP, sep = "_"))) %>%
  filter(!is.na(code_sp)) # Vérif des NAs

Coleobis<- Coleobis %>%
  setNames(c("GEN", "SP", "AB", "Num_piege", "code_sp")) %>%
  mutate(AB = as.numeric(AB)) %>%
  select(3 : 5) 

Coleo1 <- Coleobis %>%
  filter(Num_piege == 1) %>%
  group_by(code_sp) %>%
  summarise(AB = sum(AB))
ggplot(Coleo1, aes(x = code_sp, y = AB)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = AB), vjust = -0.5, size = 3) +
  labs(title = "Abondance des espèces capturées dans les pièges 1 des arbres Thèses",
       x = "Pièges entomologiques",
       y = "Abondance (n)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 9, face = "bold"),
        axis.text.x = element_text(angle = 0))

Coleo2 <- Coleobis %>%
  filter(Num_piege == 2) %>%
  group_by(code_sp) %>%
  summarise(AB = sum(AB))
ggplot(Coleo2, aes(x = code_sp, y = AB)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = AB), vjust = -0.5, size = 3) +
  labs(title = "Abondance des espèces capturées dans les pièges 1 des arbres Thèses",
       x = "Pièges entomologiques",
       y = "Abondance (n)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 9, face = "bold"),
        axis.text.x = element_text(angle = 0))

###################################################################

```


# 4. Data loader

```{r}
  # BMP Strates
BMP_Strates <- read.csv("//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Metriques_BMP_Strates_AD.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)
  # BMP Arbres
BMP_Arbres <- read.csv("//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Metriques_BMPtot_Arbres_AD.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)
  # BMP Placettes
BMP_Placettes <- read.csv("//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Metriques_BMPtot_Placette_AD.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)
  # Data entomo
entomo <- read.table(here::here("Data", "Data placettes", "DATA_placette_CANOPIX", "metriques_CB", "metric_entomo2024.txt"), sep = "\t", dec = ".", quote = "\"", stringsAsFactors = F, header = T)
  # Data matrices CB
matrices <- read.table(here::here("Data", "Data placettes", "DATA_placette_CANOPIX", "metriques_CB", "matrix_spcolsx_pieges.txt"), sep = "\t", dec = ".", quote = "\"", stringsAsFactors = F, header = T)
dimnames(matrices) # attention 1 à 6 (7: 381)
  # Data longitude et latitude
GPS <- read.csv(here::here("Data", "Data placettes", "DATA_placette_CANOPIX", "metriques_CB", "info_arbre.csv"),
sep=",", header=TRUE, stringsAsFactors = FALSE)
colnames(GPS) <- "raw"
options(digits = 15)
GPS <- separate(GPS, raw, into = c("massif", "plot", "X_L93", "Y_L93", "X_WGS84", "Y_WGS84", "sp", "note_DEPERIS", "DBH.cm", "H_arbre.m", "id_arbre"), sep = ",", convert = TRUE)
options(digits = 15)

library(vegan)

distsupra<-vegdist(matrices[,7 : 381], method="bray",na.rm = TRUE)
adonis2(matrices[,7 : 381] ~ strate, matrices, permutations = 999, method = "bray",strata = LOCA)

library(emmeans)
emmeans()
?emmeans # glmmm peut expliqué attendre CB

# refaire TOUT les modèles en séparant Final par relevé 
# Réfléchir à intégrer relevé et strates dans modèles (strate * relevé)
# Partition de variance : approche multi-variable ( proposition des métriques dendro, qui influence signif le plus et qui sur l'abondance de coleo) avec VARPAR pour mesurer la proportion de variance mais également inertie 



###

# Modifier Jeu de données entomo pour créer une colonne placette #

  # Modification de entomo pour left_join avec les métriques X
entomo <- entomo %>%
  mutate(placette = paste0(substr(LOCA, 1, 1), "_", parcelle), .before = LOCA) %>%
  arrange(placette)
  # Passage en tableau long pour l'analyse du modèle
BMP_Strates <- BMP_Strates %>%
  mutate(Vol_BMP_AC.m3 = 0, .before = "Vol_BMP_UC.m3") %>% 
  # Rajout de la colonne AC pour avoir les 4 strates
  pivot_longer(cols = 2 : 5, names_to = "strates", values_to = "Volume_BMP.m3") %>%
  mutate(num.trap = case_when(strates == "Vol_BMP_AC.m3" ~ 1,
                             strates == "Vol_BMP_UC.m3" ~ 2,
                             strates == "Vol_BMP_LC.m3" ~ 3,
                             strates == "Vol_BMP_BC.m3" ~ 4)) %>%
  rename(placette = Placette) %>%
  arrange(placette)
  # Ligne de code pour ajouter les métriques X à entomo
  # Ajout de la localisation des placettes
GPS <- GPS %>%
  arrange(id_arbre) %>%
  rename(placette = id_arbre,
         latitude = Y_L93,
         longitude = X_L93) %>%
  select(3, 4, 11)
GPS$placette <- gsub('"', '', GPS$placette) # guillements en trop
GPS <- GPS %>%
  mutate(placette = ifelse(placette == "V_169", "V_170", placette)) 

Final <- BMP_Strates %>% 
  left_join(entomo, by = c("placette" = "placette", "num.trap" = "num.trap")) %>%
  left_join(GPS, by = "placette") %>%
  select(placette, longitude, latitude, everything())
#
Final <- Final %>%
  mutate(Volume_BMP.m3 = ifelse(Volume_BMP.m3 == 0, Volume_BMP.m3 + 0.000000001, Volume_BMP.m3),
         strates = case_when(strates == "Vol_BMP_AC.m3" ~ "AC",
                             strates == "Vol_BMP_UC.m3" ~ "UC",
                             strates == "Vol_BMP_LC.m3" ~ "LC",
                             strates == "Vol_BMP_BC.m3" ~ "BC")) %>%
  mutate(id = paste0(placette, "_", num.trap))

Final$strates <- as.factor(Final$strates)
Final$placette <- as.factor(Final$placette)
Final$id <- as.factor(Final$id)
Final$strate <- as.factor(Final$strate)
```

# 5. Analyses : effet strates
Différence de strates 
## 5.1. Ab_col_all

```{r}
descdist(entomo$ab.colsx,discrete=TRUE,boot=1001)
plot(fitdist(entomo$ab.colsx,"norm"))
#
fitnb<-fitdist(entomo$ab.colsx,"nbinom")
plot(fitdist(entomo$ab.colsx,"nbinom"))
#
fitp<-fitdist(entomo$ab.colsx,"pois")
plot(fitp)
#
fitn<-fitdist(entomo$ab.colsx,"norm")
plot(fitn) # oui
#
fitlnorm<-fitdist(entomo$ab.colsx,"lnorm")
plot(fitlnorm) # oui
#
fitexp<-fitdist(entomo$ab.colsx,"exp")
plot(fitexp)
#
fitgeom<-fitdist(entomo$ab.colsx,"geom")
plot(fitgeom)
#
fitbeta<-fitdist(entomo$ab.colsx,"beta") # Pas possible, pas 0/1
plot(fitbeta)
#
fitunif<-fitdist(entomo$ab.colsx,"unif")
plot(fitunif)
#
fitg<-fitdist(entomo$ab.colsx,"gamma",method="mme")
plot(fitg) # oui

####

  # Modèle pour l'abondance, richesse spécifique
attach(Final)
longitude <- as.numeric(longitude) ; longitude
latitude <- as.numeric(latitude)
coords <- unique(Final[, c("id", "latitude", "longitude")])
coords$pos <- numFactor(scale(coords$latitude), scale(coords$longitude))
Final <- merge(Final, coords[, c("id", "pos")], by = "id", all.x = TRUE)
pos<-numFactor(scale(longitude),scale(latitude)) ; pos
ID <- id ; ID
strate <- as.factor(strate)
is.factor(strate)
is.numeric(ab.colsx)
detach(Final)
# Vérifier si id.trap bien identifiant unique pour chaque ligne #
model_ABX_BMPS <- glmmTMB(
  ab.colsx ~ strate + (1 | LOCA / placette) + exp(pos + 0 | ID) + offset(log(prop.trap.season)),
  family = "lognormal", 
  data = Final, 
  na.action = na.fail) ; summary(model_ABX_BMPS) # effet strate
#
AICc(model_ABX_BMPS)
#
model_ABX_BMPS2 <- glmmTMB(
  ab.colsx ~ 1 + (1 | LOCA / placette) + offset(log(prop.trap.season)), 
  family = "lognormal", 
  data = Final, 
  na.action = na.fail) ; summary(model_ABX_BMPS2)
#
AICc(model_ABX_BMPS2) # au minimum un delta de 2 pour l'ajustement des modèles
#
anova(model_ABX_BMPS, model_ABX_BMPS2) # 3.78e-06

####

#diagnostic glmm : ajustement, surdispersion, outliers
sim<-simulateResiduals(model_ABX_BMPS)
testUniformity(sim)#le qqplot est issu de cette commande
# id.trap si disersion (ex : (1 | LOCA / placette / id.trap)
# KS test : problème de distribution
#KS Test p-value # Dispersion test  # Outliers 
testOutliers(sim)

####

  # Test post-hoc de Tukey pour faire comparaison 2 à 2
RES<-glht(model_ABX_BMPS, linfct = mcp(strate = "Tukey"))
summary(RES)

# Est ce que supra diffère du reste : strate2 avec supra et autre canopée ou autre appellation (2 eme temps pas urgent)
```

## 5.2. Sr_col_all

```{r}
descdist(entomo$sr.colsx,discrete=TRUE,boot=1001)
plot(fitdist(entomo$sr.colsx,"norm")) # oui
#
fitnb<-fitdist(entomo$sr.colsx,"nbinom")
plot(fitdist(entomo$sr.colsx,"nbinom"))
#
fitp<-fitdist(entomo$sr.colsx,"pois")
plot(fitp)
#
fitn<-fitdist(entomo$sr.colsx,"norm")
plot(fitn) # oui
#
fitlnorm<-fitdist(entomo$sr.colsx,"lnorm")
plot(fitlnorm) # oui
#
fitexp<-fitdist(entomo$sr.colsx,"exp")
plot(fitexp)
#
fitgeom<-fitdist(entomo$sr.colsx,"geom")
plot(fitgeom)
#
fitbeta<-fitdist(entomo$sr.colsx,"beta") # Pas possible, pas 0/1
plot(fitbeta)
#
fitunif<-fitdist(entomo$sr.colsx,"unif")
plot(fitunif)
#
fitg<-fitdist(entomo$sr.colsx,"gamma",method="mme")
plot(fitg) # oui

####

model_SRX_BMPS <- glmmTMB(
  Volume_BMP.m3 ~ sr.colsx * strate, 
  family = "gaussian", 
  data = Final, 
  na.action = na.fail) ; summary(model_SRX_BMPS)
# Interaction enlevée puisque pas significatif
model_SRX2_BMPS <- glmmTMB(
  Volume_BMP.m3 ~ sr.colsx + strate, 
  family = "gaussian", 
  data = Final, 
  na.action = na.fail) ; summary(model_SRX2_BMPS)
# comparaison des modèles
AICc(model_SRX_BMPS) # -195.9065
AICc(model_SRX2_BMPS) # -199.9332

####

#diagnostic glmm : ajustement, surdispersion, outliers
sim<-simulateResiduals(model_SRX2_BMPS)
testUniformity(sim)#le qqplot est issu de cette commande 
#KS Test p-value # Dispersion test  # Outliers 
testOutliers(sim)
```

## 5.3. Ab_col_rar

```{r}
modelABRAR <- glmmTMB(
  Volume_BMP.m3 ~ ab.colsxrar + strate, 
  family = "lognormal", 
  data = Final, 
  na.action = na.fail) ; summary(modeltest)
```

## 5.4. Sr_col_rar

```{r}
modelSRRAR <- glmmTMB(
  Volume_BMP.m3 ~ sr.colsxrar + strate, 
  family = "lognormal", 
  data = Final, 
  na.action = na.fail) ; summary(modeltest)
```

## 5.5. Ab_col_com

```{r}
modelABCOM <- glmmTMB(
  Volume_BMP.m3 ~ ab.colsxcom + strate, 
  family = "lognormal", 
  data = Final, 
  na.action = na.fail) ; summary(modeltest)
```

## 5.6. Sr_col_com

```{r}
modelSRCOM <- glmmTMB(
  Volume_BMP.m3 ~ sr.colsxcom + strate, 
  family = "lognormal", 
  data = Final, 
  na.action = na.fail) ; summary(modeltest)
```

