---
title: "Métriques Revues A-D"
author: "Adrien Debout"
date: "2025-03-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Activation des Libraries

```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(stringr)
library(ggplot2)
library(FD) # pour dbFD
library(DescTools) # pour Gini
```

# Import des fichiers initiaux et settings du working directory

```{r}
  # Working diretory
setwd("C:/Users/adebout/Desktop/Adrien Debout Stage/STATS/Stats_coleo_AD/Data/Data placettes/DATA_placette_CANOPIX")
  # Import
Hauteurs <- read_excel("Hauteurs_arbres_pieges_2024.xlsx")
```

# 1. Mise en forme des données Hauteurs pour les strates
Ajout identifiant unique arbre

```{r}
  # Réduire le massif pour adapter au jeu de données principal
Hauteurs <- Hauteurs %>% mutate(massif = case_when(Massif == "Tronçais" ~ "T",
                                                     Massif == "Vierzon" ~ "V",
                                                     TRUE ~ NA_character_))

  # Renommer des valeurs particulières
Hauteurs["Num parcelle"] [Hauteurs ["Num parcelle"] == "327B"] <- "327"
Hauteurs["Num parcelle"] [Hauteurs ["Num parcelle"] == "81 Vouzeron"] <- "81"

  # Création de la colonne d'identification similaire à data_placette_Canopix
Hauteurs <- Hauteurs %>%
  group_by(massif, `Num parcelle`) %>%
  mutate(placette = ifelse(massif %in% c("V", "T"), 
                             paste0(massif, "_", `Num parcelle`), 
                             massif)) %>%
  ungroup()

  # Création d'un dataframe pour sélectionner seulement les colonnes utiles + rename des colonnes
Hauteurs_AD <- Hauteurs %>% select(placette, 
                                   `Mesure pose : piège 1 / Canopix`, 
                                   `Mesure pose : piège 2`, 
                                   `Mesure pose : piège 3`,
                                   `Mesure pose : piège 4`,
                                   `Mesure pose : arbre`, 
                                   `Mesure pose : bas houppier`)

  # Pivotemment du dataframe
Hauteurs_AD <- Hauteurs_AD %>% pivot_longer(cols = c(`Mesure pose : piège 1 / Canopix`, 
                                   `Mesure pose : piège 2`, 
                                   `Mesure pose : piège 3`,
                                   `Mesure pose : piège 4`,
                                   `Mesure pose : arbre`, 
                                   `Mesure pose : bas houppier`),
                       names_to = "mesure",
                       values_to = "Hauteur")

  # Création de la colonne Mesure avec des noms de variables simplifiés 
Hauteurs_AD <- Hauteurs_AD %>% mutate(Mesure = case_when(mesure == "Mesure pose : piège 1 / Canopix" ~ "1",
                                                     mesure == "Mesure pose : piège 2" ~ "2",
                                                     mesure == "Mesure pose : piège 3" ~ "3",
                                                     mesure == "Mesure pose : piège 4" ~ "4",
                                                     mesure == "Mesure pose : arbre" ~ "5",
                                                     mesure == "Mesure pose : bas houppier" ~ "6",
                                                     TRUE ~ NA_character_))

  # Remise en ordre pour une simplification de la lecture
Hauteurs_AD <- Hauteurs_AD %>% select(placette, mesure, Mesure, Hauteur) ; names(Hauteurs_AD) = c("placette", "mesure", "Mesure", "Hauteur")

  # Joindre les 2 data-frame
Data_Hauteurs <- Hauteurs %>% left_join(Hauteurs_AD %>% select(c(placette, Mesure, Hauteur)), by = "placette")
  # Déplacer la colonne placette au début
Data_Hauteurs <- Data_Hauteurs %>% select(placette, everything())

  # EXPORT
write.table(x = Data_Hauteurs, file = "//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Hauteurs_arbres_AD.csv", row.names = FALSE, dec=".", sep=";")
write.table(x = Hauteurs_AD, file = "//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Hauteurs_&_infos_AD.csv", row.names = FALSE, dec=".", sep=";")
```


# 2. Calcul des seuils des Hauteurs

```{r}
# Calculs des min/max (pas utile ci-dessous, à garder à titre informatif uniquement pour le code)
Data_Hauteurs2 <- Data_Hauteurs %>% 
  group_by(Mesure) %>% 
  summarise(minimum = min(Hauteur, na.rm = T),
            maximum = max(Hauteur, na.rm = T),) %>%
  ungroup()

# Calcul du demi_houppier
D <- Data_Hauteurs %>% select(placette, Mesure, Hauteur)
harbre = subset(D, Mesure == "5")
hbashouppier = subset(D, Mesure == "6")
D2 <- (harbre$Hauteur - hbashouppier$Hauteur)/2 + hbashouppier$Hauteur
demi_houppier <- as.data.frame(D2) ; names(demi_houppier) = ("Hauteur")

# Ajout des premiers seuils
Metriques_Seuils <- Hauteurs %>% select(placette)
Metriques_Seuils <- Metriques_Seuils %>% left_join(Hauteurs %>% select(c(placette, `Mesure pose : piège 1 / Canopix`, 
                                   `Mesure pose : arbre`, 
                                   `Mesure pose : bas houppier`,)), by = "placette")
# Renommer les colonnes
names(Metriques_Seuils) = c("placette", "Seuil_superieur_(AC)", "Seuil_inferieur_(AC)", "Seuil_inferieur_(LC)")

# Rajouter les différents seuils manquant
Metriques_Seuils <- Metriques_Seuils %>% mutate("Seuil_superieur_(UC)" = Hauteurs$`Mesure pose : arbre`, .before = "Seuil_inferieur_(LC)")

Metriques_Seuils <- Metriques_Seuils %>% mutate("Seuil_inferieur_(UC)" = demi_houppier$Hauteur, .before = "Seuil_inferieur_(LC)")

Metriques_Seuils <- Metriques_Seuils %>% mutate("Seuil_superieur_(LC)" = demi_houppier$Hauteur, .before = "Seuil_inferieur_(LC)")

Metriques_Seuils <- Metriques_Seuils %>% mutate("Seuil_inferieur_(LC)" = Hauteurs$`Mesure pose : bas houppier`)

Metriques_Seuils <- Metriques_Seuils %>% mutate("Seuil_superieur_(BC)" = Hauteurs$`Mesure pose : bas houppier`)

# Vecteur de 20 valeurs = 0 pour le Seuil_inferieur_(BC)
A <- rep(0, 20)

# Dernier seuil
Metriques_Seuils <- Metriques_Seuils %>% mutate("Seuil_inferieur_(BC)" = A)

# S'assurer que tous les seuils soient bien en numérique
Metriques_Seuils <- Metriques_Seuils %>% mutate_at(c(2:9), as.numeric)

# EXPORT
write.table(x = Metriques_Seuils, file = "//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Metriques_Seuils_Strates_AD.csv", row.names = FALSE, dec=".", sep=";")
```

## Bois Mort Perché (BMP)
Origine du code : Mathéo

```{r}
# IMPORT Bois Mort Perche
BMP <- read.csv("bois_mort_perche.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)
# IMPORT Seuils Strates
MSS <- read.csv("//no-datafile.inra.local/Biodiversite/projets/Bois_mort/Canopee/These_Balvay/Stagiaires/Adrien Debout - 03-02 au 01-08-2025/Data/Metriques_Seuils_Strates_AD.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)

# Faire correspondre les apellations pour la Placette (ex : T_118 et non T_118_1)
# Séparer l'id
BMP2 <- BMP %>% separate(id_arbre, into = c("massif", "id", "arbre", sep ="_"))
# joindre pour créer la colonne placette
BMP2$placette <- paste(BMP2$massif, BMP2$id, sep = "_")
# Placer la colonne placette devant
BMP <- BMP2 %>% select(placette, everything())
# Supprimer les colonnes inutiles
BMP <- BMP %>% select(-"_")

# Filtrer pour seulement les arbres thèses (ex : ._..._1)

BMP <- BMP %>% filter(arbre == "1")

# Crée une colonne de la strate à laquelle le BMP appartient
bois_mort_brut <- read.csv("bois_mort_brut.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)

bois_mort_brut2 <- 
  bois_mort_brut%>%mutate(strate_BMP = case_when
                          (H_BMP.m <= MSS$Seuil_superieur_.BC. ~ 'BC'))

# VOIR SUR BMP BRUT POUR LE CALCUL DU VOL DE BOIS MORT



# ajout de variables à bois_mort_brut
bois_mort_brut <- left_join(bois_mort_brut, TREMs_obs[,c(1,3,4,5,15,19,21,22,23,24,44,45)],  by = "id_arbre")
bois_mort_brut <- distinct(bois_mort_brut)

# calcul du volume des branches mortes avec la formule de Huber : V =(pi*dm²*L)/4
bois_mort_brut$vol.m3 <- (pi*bois_mort_brut$diam_BMP.m^2*bois_mort_brut$long_BMP.m)/4

# crée une colonne de la strate à laquelle le BMP appartient
bois_mort_brut <- bois_mort_brut%>%mutate(strate_BMP=case_when(H_BMP.m<= 2 ~ '1p',
                                                     H_BMP.m>2 & H_BMP.m<= H_bas_houppier.m ~ '2t',
                                                     H_BMP.m>H_bas_houppier.m
                                                     & H_BMP.m<=(H_bas_houppier.m+1/3*(L_houppier.m)) ~ 'h1',
                                                     H_BMP.m>(H_bas_houppier.m+1/3*(L_houppier.m))
                                                     & H_BMP.m<=(H_bas_houppier.m+2/3*(L_houppier.m)) ~ 'h2',
                                                     H_BMP.m>=(H_bas_houppier.m+2/3*(L_houppier.m)) ~ 'h3'))

# EXPORT
write.table(x = bois_mort, file = here::here("Data", "bois_mort_perche.csv"), row.names = FALSE, dec=".", sep=";")
bois_mort <- read.table(here::here("Data","bois_mort_perche.csv"), sep=";", header=TRUE, stringsAsFactors = FALSE)

colnames(BMP)[colnames(BMP) == "vol.m2"] <- "vol.m3" # corrige

```